### ISSUE TITLE
Unique IDs are reset to 1 when Frame Type is changed

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#112]
The /Default/NDArrayUniqueIdIn in the hdffile is reset to 1  when changing frame type (dark/flat/projection).
To easily manage dropped frames, It would be better to have a unique id that is not reset. 

Who is controlling the reset of the unique ID?

**Comment by MarkRivers** [comment]
> Who is controlling the reset of the unique ID?

That is controlled by the UniqueIDMode PV in ADSpinnaker.
 https://areadetector.github.io/master/ADSpinnaker/ADSpinnaker.html 

If is it set to "Camera" then it uses the UniqueID that the camera itself generates.  That is reset each time a new acquisition is started, i.e. every time ADAcquire is set to 1.

If you change it to Driver then the ADSpinnaker driver will generate the UniqueID and it won't reset.  It just keeps incrementing the value of UniqueID until the IOC is restarted.

**Comment by MarkRivers** [comment]
The disadvantage of using "Driver" is that you won't know which frame has been dropped because the driver can't know that. It just knows that it did not get as many frames as requested.  If you use "Camera" then you can tell which frame was dropped.

**Comment by decarlof** [comment]
thanks. I will then keep it set to "Camera" and add logic to find the unique IDs of the projections. My goal is to add a theta array that is correct even when there are dropped projections. This is not that critical for equally spaced angles but it is for multiple rotation interlaced.
