### ISSUE TITLE
FlatFieldValue is missing from tomoscan.adl

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#143]
it looks the FlatFieldValue PV (defined in .template) is not accessible from any medm screen.

FlatFieldValue is the te constant flat field value for every pixel, typically used when FlatFieldMode=None.

Shall I put it in the tomoscan.adl or somewhere else?

**Comment by MarkRivers** [comment]
Good point.  I think putting it in tomoscan.adl is OK.

**Comment by decarlof** [comment]
Below are tomoScan.adl as it looked before and after adding the FlatFiledValue.

Before:
![tomoScan_before](https://user-images.githubusercontent.com/5884150/169590138-582e0d9a-0fa2-4d91-accf-9f40231c1636.png)


After:
![tomoScan_after](https://user-images.githubusercontent.com/5884150/169590163-1b43b2cb-4047-43dc-aa48-720fe61e58bf.png)

**Comment by decarlof** [comment]
Below are tomoScan.adl as it looked before and after adding the FlatFiledValue.

Before:
![tomoScan_before](https://user-images.githubusercontent.com/5884150/169591546-7c6ab42a-4acd-4f62-b1af-9f68745bdbfe.png)


After:
![tomoScan_after](https://user-images.githubusercontent.com/5884150/169591769-f7355d5b-9e3f-4ef5-bbc8-060917996b04.png)
