### ISSUE TITLE
adding the last saved file name on the main tomoScan medm screen

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#161]
In many situation is convenient to know name of the last saved file without having to check on the file system or on the file writer plugin. If you are ok we can add it on the main tomoScan.adl to look something like this:

<img width="580" alt="Screen Shot 2022-11-18 at 16 55 32" src="https://user-images.githubusercontent.com/5884150/202816557-236e142e-0cd7-414e-a2c6-944be073949a.png">

but there are some issues:
- in the above medm screen I needed to pass the camera and plugin prefix (so if someone is changing camera we need to change the medm screen prefixes which I don't think is acceptable)
- how to remove the path and just display the last file name?

If are ok with the change, I  can address the above adding a new tomoScan PV called LastFileName that updates at the beginning of each scan.

**Comment by MarkRivers** [comment]
Will it read the last file name from the HDF5 plugin?  I think it's OK to have the path, that can be useful information.  We can make the font smaller to fit more on the screen?

**Comment by decarlof** [comment]
yes the name will be read from the HDF5 plugin and we can make the font smaller. I would still create a tomoScan served PV called LastFileName with value = to the HDF5 plugin. This way the tomoScan medm screen does not depend on the camera/hdf5 prefix.

**Comment by MarkRivers** [comment]
I agree with that approach.

**Comment by decarlof** [comment]
[This commit](https://github.com/decarlof/tomoscan/commit/8a8da7c4e4710acb02d9d5e4ce00fb94349ae6c5) addresses this ticket.
