### ISSUE TITLE
tomoscan logo

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#166]
Sorry I merged [this](https://github.com/tomography/tomoscan/pull/165/commits/f9d193b020172293fdf925b6ba13ac66e6b88ef5) by mistake. I meant to ask if you all agree with the logo. It is similar to the one we use for [tomopy](https://tomopy.readthedocs.io/en/stable/_images/tomopy-logo-wide.svg) and [tomostream](https://tomostream.readthedocs.io/en/latest/_images/tomostream-logo.png). 

Let me know if you prefer something else.

**Comment by MarkRivers** [comment]
No problem, that looks good to me.
