### ISSUE TITLE
tomoscan base class does not set the HDF5 file location for the data

### ISSUE THREAD

**Issue by MarkRivers** [tomography/tomoscan#27]
The tomoscan base class should be setting the location in the HDF5 file to save the data.

I think the way that tomoscan_2bm and pull request #22 for base class handle this is not ideal.  They are using the FrameType PV in the detector, and writing strings like "/exchange/data_dark" into the enum strings.  My reasons for not liking that are:
- Those strings will be visible to the user, and they are not really frame-type choices (which might be 'Dark field', 'Flat field', 'Projection', rather they are locations in an HDF5 file.
- The FrameType field might be used for a completely different hardware purpose with some detectors.

I suggest that instead of using FrameType we simply create a new PV in tomoScan.template that controls the location in the HDF5 file.  That is the PV that the detector attribute XML file should be using, and that attribute is what should be in the HDF5 layout XML file.

While implementing the above ideas, I also realized that the base class implementations of collect_dark_fields(), collect_flat_fields(), and collect_projections() in tomoscan.py can actually be used to implement a number of common operations, and thus be called from the derived class.  This does 2 things:
- Simplifies the tomoscan.fly_scan() because those base class functions take care of the following things:
  - Setting the status message
  - Open/close shutter
  - Move sample in/out
  - Set the HDF5 data location
- Simplifies the derived class implementation of these functions.  They now call the base class method first to handle the common operations.

**Comment by decarlof** [comment]
>     * Those strings will be visible to the user, and they are not really frame-type choices (which might be 'Dark field', 'Flat field', 'Projection', rather they are locations in an HDF5 file.
> 
>     * The FrameType field might be used for a completely different hardware purpose with some detectors.

The use of FrameType was a local solution to get the job done, but I agree will not work in general and should be replaced. 

For 2-BM, 32-ID etc. we let the user pick only the SampleName, the rest to generate:

(TOP)/YearMonth/UserLastName/XXX_sampleName.h5

is automatically generated using PVs update from the scheduling system and for XXX the camera file counter

I assume that:
>       * Set the HDF5 data location

is fully compatible with it.

**Comment by MarkRivers** [comment]
I think that the PR is compatible with populating the PVs from the scheduling system and just the SampleName.

To do this you should generate this string (TOP)/YearMonth/UserLastName/ in your derived class and put it into FilePath from tomoScan.template.  It will then get automatically copied to the file plugin FilePath.

Similarly write XXX_sampleName to FileName from tomoScan.template, and it will be copied to the file plugin.

Will this work for you?

**Comment by decarlof** [comment]
yes this will work!

**Comment by MarkRivers** [comment]
There was a related issue.  tomoscan is not limited to writing HDF5 files, it can also write netCDF or other files.  With HDF5 it can store all data (dark, flat, projection) in a single file, or each in its own file.  This is controlled by the derived class.

When writing netCDF or HDF5 with each frame type in a separate file we need a PV to indicate what  frame type that file contains.

I added a new FrameType record to tomoScan.template and tomoScan_settings.req.  I have added this PV to the detector attributes file and the HDF5 layout file at 13-BM.  It works correctly, each file has a dataset that gives the frame type.
```
corvette:2020/Run1/Test>h5dump -d /exchange/frame_type Test_H_001.h5 | more
HDF5 "Test_H_001.h5" {
DATASET "/exchange/frame_type" {
   DATATYPE  H5T_STRING {
      STRSIZE 256;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SIMPLE { ( 1 ) / ( H5S_UNLIMITED ) }
   DATA {
   (0): "FlatField"
   }
...

corvette:2020/Run1/Test>h5dump -d /exchange/frame_type Test_H_002.h5 | more
HDF5 "Test_H_002.h5" {
DATASET "/exchange/frame_type" {
   DATATYPE  H5T_STRING {
      STRSIZE 256;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SIMPLE { ( 1 ) / ( H5S_UNLIMITED ) }
   DATA {
   (0): "Projection"
   }
```

**Comment by MarkRivers** [comment]
This issue has been fixed.
