### ISSUE TITLE
FrameType PV assignement error

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#29]
[self.epics_pvs['FrameType'].put('DarkField') ](https://github.com/tomography/tomoscan/blob/560678f02bf1389699a2d22447e17adc604d3450/tomoscan/tomoscan.py#L561)
ValueError: invalid literal for int() with base 10: b'DarkField'

An option to solve it is to define 

```
FrameTypeData = 0
FrameTypeDark = 1
FrameTypeWhite = 2

```
and 

`self.epics_pvs['FrameType'].put(FrameTypeDark)`

**Comment by MarkRivers** [comment]
I am not getting that error. It is working fine for me.  However, I had failed to do a push with some of my latest changes.

It must be a problem with your repository.

FrameType is a PV in tomoScan.template and is defined in tomoScan_settings.req, so it will be created automatically.

I reverted your commit.  Please do a pull and see if it works.

**Comment by MarkRivers** [comment]
I just tested with the master branch, but using tomoscan_13bm_single_file.py code rather than tomoscan_13bm.py.

It worked fine, no errors.

**Comment by decarlof** [comment]
Ok it works now for me too.Thanks.
