### ISSUE TITLE
Set up Webhook to automatically publish on tomoscan.readthedocs.io on push

### ISSUE THREAD

**Issue by MarkRivers** [tomography/tomoscan#33]
I'd like to have the online documentation be updated on each push.  I have done that for this repository:
https://github.com/epics-modules/Dante

which publishes here:
https://epics-dante.readthedocs.io/en/latest/

@decarlof if you add me as a maintainer of tomoscan on readthedocsI think I can set it up, or you could do it yourself.

**Comment by decarlof** [comment]
I re-synced the webhook and add @MarkRivers as maintainer

**Comment by MarkRivers** [comment]
I found that when I did a push it was not updating the docs at readthedocs.

I added a Webhook to the github.com/tomoscan repository:
https://github.com/tomography/tomoscan/settings/hooks/207847508

Now it works.

**Comment by decarlof** [comment]
ah that is strange, I did a re-sync of the webhook (there was a resync button under the warning that the webhook was not synched), the warming went away and the page rebuilt.  I thought that fixed, instead it did not and needed to be done manually. Thanks for catching it.
