### ISSUE TITLE
beamline specific tomoScan.substitutions

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#49]
@MarkRivers where is the best place in the repository to put a copy of the beamline specific tomoScan.substitutions file? Can I save it as:

`iocBoot/iocTomoScan/tomoScan.substitutions_2BM`

**Comment by MarkRivers** [comment]
Actually we should rename iocTomoScan to iocTomoScan_13BM, and make a new directory iocTomoScan_2BM.

**Comment by decarlof** [comment]
even better, I was just now about to ask about the st.cmd for 2-BM ...
