### ISSUE TITLE
ExposureTime PV

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#6]
Question: 

In the docs at https://github.com/tomography/tomoscan/blob/master/docs/source/demo.rst

The Server mode records PV   

* - $(P)$(R)ExposureTime
    - bo
    - Values written to this record will be copied to the camera AcquireTime PV.

should be renamed to avoid conflict with 

areaDetector camera
-------------------

  * - $(P)$(R)ExposureTime
    - ao
    - The exposure time in seconds.  Currently the same time is used for dark fields, flat fields, and projections.

?

If so the new server PV should be added to https://github.com/tomography/tomoscan/blob/master/docs/demo/13bm/TomoCollect.template

**Comment by decarlof** [comment]
I think I got it. In  https://github.com/tomography/tomoscan/blob/master/docs/source/demo.rst we should have only one instance under the required record.

**Comment by MarkRivers** [comment]
I'll check it out.

I am quite happy, the server mode is now working.  I can start scans from medm or any other CA client.  I can abort scans with a CA client, or with ^C.  I am working on some improvements to the status updates, etc.  I will be updating the documentation with these as I finish them.
