### ISSUE TITLE
tomoscan cli does not handle correctly X (Y) scans when flat field axis is set to Y (X) or collect flat field is set to None

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#66]
Currently tomoscan cli is using SampleInX and SampleInY to set the data collection position in vertical/horizontal scans. This is a mistake and will not work if these axises are not selected as flat filed axis or if collect flat field is set to None. In this cases we should move the SampleX and SampleY motor directly.

**Comment by MarkRivers** [comment]
Yes, that is what I meant to say in response to an earlier question about whether my example scan should be using the SampleInY to scan the height.  That is why I used the actual motor itself.

**Comment by decarlof** [comment]
correct, and if the axis are selected for flat field then the vertical scan position will be overwritten by the SampleInY position. I just made a change that should be able to handle both cases.

**Comment by decarlof** [comment]
> Yes, that is what I meant to say in response to an earlier question about whether my example scan should be using the SampleInY to scan the height. That is why I used the actual motor itself.

still in your example at #64, if you scan SampleY and the tomoscan is set to collect a flat field of the beginning using Y the scan position will be overwritten by the SampleInY position. If flat are taken moving SampleX or at the end of the scan, the example is fine.
Perhaps we should add a warning in the [demo docs](https://tomoscan.readthedocs.io/en/latest/demo.html) so people are aware of it.

**Comment by MarkRivers** [comment]
I just added a  note to the demo docs and pushed to Github.  I also pushed some other minor changes, including new autoconverted versions of the 2BM medm screen.

**Comment by decarlof** [comment]
perfect!
