### ISSUE TITLE
Proposal title length limit to 40 character

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#73]
does it make change to change in tomoScan_XXX.template:

```
record(stringout, "$(P)$(R)ProposalTitle")
{
   field(VAL,  "Unknown")
}
```

to

```
record(waveform, "$(P)$(R)ProposalTitle") 
{
    field(SCAN, "Passive")
    field(DTYP, "Soft Channel")
    field(NELM, "256")
    field(FTVL, "CHAR")
}
```

to allow for longer than 40 characters titles?

**Comment by MarkRivers** [comment]
That looks good. We should probably do that for some other information records as well. I think we need to make sure the detector XML file specifies to read as a string and not “native”. I’m on vacation and can’t check myself.

**Comment by decarlof** [comment]
All user info in the [detector XML file](https://github.com/data-exchange/dxfile/blob/master/doc/demo/areadetector/13-BM/tomoDetectorAttributes.xml) are set as  dbrtype="DBR_STRING". Let me change for now only ProposalTitle and UserInstitution as I am testing a new version of [DMagic](https://github.com/xray-imaging/DMagic) to read these from the [APS scheduling](https://schedule.aps.anl.gov/) system.
