### ISSUE TITLE
adl files

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#8]
@MarkRivers can you add the source files (adl?) you generate the screen shots. Probably a good location is https://github.com/tomography/tomoscan/tree/master/docs/demo/13bm

**Comment by MarkRivers** [comment]
@decarlof I have been thinking about this.  This repository could actually be viewed as an EPICS module, like motor, asyn, etc.  If it were in that structure it would have a tomoscanApp/Db directory where we would put the .template and autosave .req files.  It would also have a tomoscanApp/op/adl directory where we would put the medm screens.  The tomoscanApp/op directory would contain a Makefile that would automatically convert the .adl files to caQtDM, CSS/BOY, CSS/Phoebus, and EDM files.  There could be an example tomoscan/iocBoot directory where we have an example startup script and .substitutions file.  This structure would be the same as all other EPICS modules.

We would have to decide where to put the Python code (tomoscanApp/src?).  But there are other EPICS modules with Python code, so we have some examples to copy.

One option would to move the repository to github.com/epics-modules.  On the other hand we could leave it where it is on Github, but move things around so it has the structure of an EPICS module, and things will be in the places that people expect them, and where Makefile rules can do the correct thing, installing .template and .req files into tomoscan/db, etc.

**Comment by decarlof** [comment]
@MarkRivers I agree: we should put all the epics part in the expected directory structure and the  python code should stay together. I liked the tomography/tomoscan because puts the center on tomography (=where other tomography people are familiar in finding tools) but any other location would be fine; the majority will reach the repository through the docs anyway

**Comment by MarkRivers** [comment]
I am working on adding those directories and files.  I will push once I have it working.

**Comment by MarkRivers** [comment]
I have finished this.  tomoscan is now a normal EPICS support module, with: 
- tomoScanApp/Db containing the example database and autosave settings files.
- tomoScanApp/op containing example medm, caQtDM, edl, CSS/Boy, and CSS/Phoebus OPI files.
- tomoScanApp/src that builds an IOC application that can run the database.
- iocBoot/iocTomoScan with example startup script, and scripts to start the IOC and medm.

The Python code is still in a sub-directory called tomoscan, but I propose that we rename that to Python.

I have changed tomoscan.py so it only needs to parse a single file to get all of the required PVs to connect to, while in the previous version it needed 2 files.  This file is the tomoScan_settings.req autosave request file.  The PVs that we don't want autosave to actually save but we want tomoscan to read are in this file in special comment lines.

I will work on updating the documentation next.

**Comment by MarkRivers** [comment]
I updated the documentation, but when I tried to push @decarlof had modified in a conflicting way.  I will try to resolve the conflicts.

**Comment by decarlof** [comment]
@MarkRivers sorry I see this only now and I realized we bumped into each other. I think all is solve  and docs built OK [here](https://tomoscan.readthedocs.io/en/latest/).

**Comment by decarlof** [comment]
@MarkRivers 

> The Python code is still in a sub-directory called tomoscan, but I propose that we rename that to Python.

usually the folder where the python code is matches the name of the python library (created by python setup.py install), but I think can be changed @dgursoy may have a better suggestion.

**Comment by MarkRivers** [comment]
This is done now that we have tomoScanApp.
